/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ogofhernpbadexoclfdr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nb2ZoZXJucGJhZGV4b2NsZmRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NTA0NjIsImV4cCI6MjA3NzMyNjQ2Mn0.dQutjun7VoXszCc-P9HLxO3Dph_G5QBPigZ-p5_-TjY"